plugins {
    id 'java-library'
}

dependencies {
    api 'org.springframework:spring-web'
    api 'org.springframework:spring-context'
    api 'jakarta.validation:jakarta.validation-api'
    api 'org.slf4j:slf4j-api'
    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    api 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
}
